name: Publish

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: Echo secring file from secrets
      run: 'echo "$GPG_PRIVATE_KEY" > "$HOME/secring.gpg"'
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish with Gradle Nexus Publish Plugin
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=E4893EC0 -Psigning.password="$GPG_PASSPHRASE" -Psigning.secretKeyRingFile="$HOME/secring.gpg"
      env: 
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
